const should = require('should');
should.config.checkProtoEql = false;
const sinon = require('sinon');
const proxyquire = require('proxyquire');
const CURRENT_VERSION = 11.2;

const createLayerMetadataFieldsSpy = sinon.spy(function () {
  return ['fields'];
});
const fields = {
  LayerFields: {
    create: createLayerMetadataFieldsSpy,
  },
};

const TableLayerMetadata = proxyquire('./table-layer-metadata', {
  '../helpers/fields': fields,
});

describe('TableLayerMetadata', () => {
  beforeEach(() => {
    createLayerMetadataFieldsSpy.resetHistory();
  });

  it('calling with new should return default metadata', () => {
    const tableLayerMetadata = new TableLayerMetadata();
    tableLayerMetadata.should.deepEqual({
      currentVersion: CURRENT_VERSION,
      id: 0,
      name: 'Not Set',
      type: 'Table',
      displayField: '',
      description:
        'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
      copyrightText:
        'Copyright information varies by provider. For more information please contact the source of this data.',
      defaultVisibility: true,
      isDataVersioned: false,
      hasContingentValuesDefinition: false,
      supportsAppend: false,
      supportsCalculate: false,
      supportsASyncCalculate: false,
      supportsTruncate: false,
      supportsAttachmentsByUploadId: false,
      supportsAttachmentsResizing: false,
      supportsRollbackOnFailureParameter: false,
      supportsStatistics: true,
      supportsExceedsLimitStatistics: false,
      supportsAdvancedQueries: true,
      supportsValidateSql: false,
      supportsLayerOverrides: false,
      supportsTilesAndBasicQueriesMode: true,
      supportsFieldDescriptionProperty: false,
      supportsQuantizationEditMode: false,
      supportsApplyEditsWithGlobalIds: false,
      supportsReturningQueryGeometry: false,
      advancedQueryCapabilities: {
        supportsPagination: true,
        supportsQueryAttachmentsCountOnly: false,
        supportsPaginationOnAggregatedQueries: false,
        supportsQueryRelatedPagination: false,
        supportsQueryWithDistance: false,
        supportsReturningQueryExtent: true,
        supportsStatistics: true,
        supportsOrderBy: true,
        supportsDistinct: true,
        supportsQueryWithResultType: false,
        supportsSqlExpression: false,
        supportsAdvancedQueryRelated: false,
        supportsCountDistinct: false,
        supportsPercentileStatistics: false,
        supportedSpatialAggregationStatistics: [],
        supportsLod: false,
        supportsQueryWithLodSR: false,
        supportedLodTypes: [],
        supportsReturningGeometryCentroid: false,
        supportsReturningGeometryEnvelope: false,
        supportsQueryWithDatumTransformation: false,
        supportsCurrentUserQueries: false,
        supportsHavingClause: false,
        supportsOutFieldSQLExpression: false,
        supportsMaxRecordCountFactor: false,
        supportsTopFeaturesQuery: false,
        supportsDisjointSpatialRel: false,
        supportsQueryWithCacheHint: false,
        supportedOperationsWithCacheHint: [],
        supportsQueryAnalytic: false,
        supportsDefaultSR: false,
        supportsFullTextSearch: false,
        advancedQueryAnalyticCapabilities: {},
        advancedEditingCapabilities: {},
      },
      useStandardizedQueries: true,
      allowGeometryUpdates: false,
      hasAttachments: false,
      htmlPopupType: 'esriServerHTMLPopupTypeNone',
      hasM: false,
      hasZ: false,
      objectIdField: 'OBJECTID',
      uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
      globalIdField: '',
      typeIdField: '',
      dateFieldsTimeReference: {
        timeZone: 'UTC',
        respectsDaylightSaving: false,
      },
      preferredTimeReference: null,
      templates: [],
      supportedQueryFormats: 'JSON,geojson,PBF',
      supportedAppendFormats: '',
      supportedExportFormats: '',
      supportedSpatialRelationships: [
        'esriSpatialRelIntersects',
        'esriSpatialRelContains',
        'esriSpatialRelEnvelopeIntersects',
        'esriSpatialRelWithin',
      ],
      supportedContingentValuesFormats: '',
      hasStaticData: false,
      maxRecordCount: 2000,
      standardMaxRecordCount: 2000,
      standardMaxRecordCountNoGeometry: 2000,
      tileMaxRecordCount: 2000,
      maxRecordCountFactor: 1,
      fields: [],
      relationships: [],
      capabilities: 'Query',
      ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
      types: [],
      timeInfo: {},
    });
  });

  describe('mixinOverrides', () => {
    it('uses fields creator helper', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      const geojson = {
        features: [
          {
            type: 'FeatureCollection',
            properties: {},
          },
        ],
      };
      tableLayerMetadata.mixinOverrides(geojson);

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
      createLayerMetadataFieldsSpy.callCount.should.equal(1);
      createLayerMetadataFieldsSpy.firstCall.args.should.deepEqual([geojson]);
    });

    it('defers to "layerId" option for "id"', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { layerId: '2' });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 2,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('uses "id" option when no "layerId" option', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { id: 3 });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 3,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('defers to "displayField" option for "displayField"', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { displayField: 'hellow' });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'hellow',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"idField" option used in multiple overrides', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { idField: 'fluffy' });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'fluffy',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'fluffy',
        uniqueIdField: { name: 'fluffy', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"hasZ" option used when present in metadata', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { hasZ: true });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: true,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"hasStaticData" option used if a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { hasStaticData: true });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: true,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"hasStaticData" option ignored if not a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { hasStaticData: 'true' });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('empty "capabilities" option ignored', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { capabilities: {} });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('defer to "capabilities.list" option if defined ', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides(
        {},
        { capabilities: { list: 'hello,world' } },
      );

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'hello,world',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('add "Extract" to default "capabilities" if capabilities.extract is truthy', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides(
        {},
        { capabilities: { extract: true } },
      );

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query,Extract',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"hasStaticData" option used if a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { hasStaticData: true });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: true,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"supportsPagination" option ignored if not a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { supportsPagination: 'false' });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"supportsPagination" option used if a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { supportsPagination: false });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: false,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"hasAttachments" option used if a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { hasAttachments: true });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: true,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('"hasAttachments" option ignored if not a boolean value', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides({}, { hasAttachments: 'true' });

      tableLayerMetadata.should.deepEqual({
        currentVersion: CURRENT_VERSION,
        id: 0,
        name: 'Not Set',
        type: 'Table',
        displayField: 'OBJECTID',
        description:
          'This is a feature service exposed with Koop. For more information go to https://github.com/koopjs/koop.',
        copyrightText:
          'Copyright information varies by provider. For more information please contact the source of this data.',
        defaultVisibility: true,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: [],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 2000,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: [],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: {},
      });
    });

    it('use supported options for direct overrides', () => {
      const tableLayerMetadata = new TableLayerMetadata();
      tableLayerMetadata.mixinOverrides(
        {},
        {
          name: 'Hank Williams',
          relationships: ['something'],
          description: 'There is a tear in my beer.',
          copyrightText: 'copyright-text',
          templates: ['templates'],
          timeInfo: { time: 'June of 44' },
          maxRecordCount: 9999,
          defaultVisibility: false,
          currentVersion: 90.99,
        },
      );

      tableLayerMetadata.should.deepEqual({
        currentVersion: 90.99,
        id: 0,
        name: 'Hank Williams',
        type: 'Table',
        displayField: 'OBJECTID',
        description: 'There is a tear in my beer.',
        copyrightText: 'copyright-text',
        defaultVisibility: false,
        isDataVersioned: false,
        hasContingentValuesDefinition: false,
        supportsAppend: false,
        supportsCalculate: false,
        supportsASyncCalculate: false,
        supportsTruncate: false,
        supportsAttachmentsByUploadId: false,
        supportsAttachmentsResizing: false,
        supportsRollbackOnFailureParameter: false,
        supportsStatistics: true,
        supportsExceedsLimitStatistics: false,
        supportsAdvancedQueries: true,
        supportsValidateSql: false,
        supportsLayerOverrides: false,
        supportsTilesAndBasicQueriesMode: true,
        supportsFieldDescriptionProperty: false,
        supportsQuantizationEditMode: false,
        supportsApplyEditsWithGlobalIds: false,
        supportsReturningQueryGeometry: false,
        advancedQueryCapabilities: {
          supportsPagination: true,
          supportsQueryAttachmentsCountOnly: false,
          supportsPaginationOnAggregatedQueries: false,
          supportsQueryRelatedPagination: false,
          supportsQueryWithDistance: false,
          supportsReturningQueryExtent: true,
          supportsStatistics: true,
          supportsOrderBy: true,
          supportsDistinct: true,
          supportsQueryWithResultType: false,
          supportsSqlExpression: false,
          supportsAdvancedQueryRelated: false,
          supportsCountDistinct: false,
          supportsPercentileStatistics: false,
          supportedSpatialAggregationStatistics: [],
          supportsLod: false,
          supportsQueryWithLodSR: false,
          supportedLodTypes: [],
          supportsReturningGeometryCentroid: false,
          supportsReturningGeometryEnvelope: false,
          supportsQueryWithDatumTransformation: false,
          supportsCurrentUserQueries: false,
          supportsHavingClause: false,
          supportsOutFieldSQLExpression: false,
          supportsMaxRecordCountFactor: false,
          supportsTopFeaturesQuery: false,
          supportsDisjointSpatialRel: false,
          supportsQueryWithCacheHint: false,
          supportedOperationsWithCacheHint: [],
          supportsQueryAnalytic: false,
          supportsDefaultSR: false,
          supportsFullTextSearch: false,
          advancedQueryAnalyticCapabilities: {},
          advancedEditingCapabilities: {},
        },
        useStandardizedQueries: true,
        allowGeometryUpdates: false,
        hasAttachments: false,
        htmlPopupType: 'esriServerHTMLPopupTypeNone',
        hasM: false,
        hasZ: false,
        objectIdField: 'OBJECTID',
        uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
        globalIdField: '',
        typeIdField: '',
        dateFieldsTimeReference: {
          timeZone: 'UTC',
          respectsDaylightSaving: false,
        },
        preferredTimeReference: null,
        templates: ['templates'],
        supportedQueryFormats: 'JSON,geojson,PBF',
        supportedAppendFormats: '',
        supportedExportFormats: '',
        supportedSpatialRelationships: [
          'esriSpatialRelIntersects',
          'esriSpatialRelContains',
          'esriSpatialRelEnvelopeIntersects',
          'esriSpatialRelWithin',
        ],
        supportedContingentValuesFormats: '',
        hasStaticData: false,
        maxRecordCount: 9999,
        standardMaxRecordCount: 2000,
        standardMaxRecordCountNoGeometry: 2000,
        tileMaxRecordCount: 2000,
        maxRecordCountFactor: 1,
        fields: ['fields'],
        relationships: ['something'],
        capabilities: 'Query',
        ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
        types: [],
        timeInfo: { time: 'June of 44' },
      });
    });
  });

  it('static method "normalizeInput" should create expected geojson and default options', () => {
    const { geojson, options } = TableLayerMetadata.normalizeInput(
      {
        features: ['feature'],
      },
      {
        params: { layer: '99' },
      },
    );
    geojson.should.deepEqual({ features: ['feature'] });
    options.should.deepEqual({
      capabilities: {},
      layerId: '99',
    });
  });

  it('static method "normalizeInput" should merge capabilities', () => {
    const { geojson, options } = TableLayerMetadata.normalizeInput(
      {
        features: ['feature'],
        metadata: {
          capabilities: 'list,of,stuff',
        },
        capabilities: {
          world: 'hellow',
        },
      },
      {
        params: { layer: '99' },
      },
    );
    geojson.should.deepEqual({ features: ['feature'] });
    options.should.deepEqual({
      layerId: '99',
      capabilities: {
        list: 'list,of,stuff',
        world: 'hellow',
      },
    });
  });

  it('static method "normalizeInput" should defer to metadata description', () => {
    const { geojson, options } = TableLayerMetadata.normalizeInput(
      {
        features: ['feature'],
        metadata: {
          description: 'Metadata description',
        },
      },
      {
        params: { layer: '99' },
        app: {
          locals: {
            config: {
              featureServer: {
                description: 'Overrides default layer description.',
              },
            },
          },
        },
      },
    );
    geojson.should.deepEqual({ features: ['feature'] });
    options.should.deepEqual({
      layerId: '99',
      description: 'Metadata description',
      capabilities: {},
    });
  });

  it('static method "create" should normalize input, call constructor, and mixin-overrides ', () => {
    const tableLayerMetadata = TableLayerMetadata.create(
      {
        features: ['feature'],
        metadata: {
          foo: 'bar',
          displayField: 'myField',
          capabilities: 'list,of,stuff',
        },
        capabilities: {
          world: 'hellow',
        },
      },
      {
        params: { layer: '99' },
        app: {
          locals: {
            config: {
              featureServer: {
                currentVersion: 90.99,
                description: 'Overrides default layer description.',
              },
            },
          },
        },
      },
    );

    tableLayerMetadata.should.deepEqual({
      currentVersion: 90.99,
      id: 99,
      name: 'Not Set',
      type: 'Table',
      displayField: 'myField',
      description: 'Overrides default layer description.',
      copyrightText:
        'Copyright information varies by provider. For more information please contact the source of this data.',
      defaultVisibility: true,
      isDataVersioned: false,
      hasContingentValuesDefinition: false,
      supportsAppend: false,
      supportsCalculate: false,
      supportsASyncCalculate: false,
      supportsTruncate: false,
      supportsAttachmentsByUploadId: false,
      supportsAttachmentsResizing: false,
      supportsRollbackOnFailureParameter: false,
      supportsStatistics: true,
      supportsExceedsLimitStatistics: false,
      supportsAdvancedQueries: true,
      supportsValidateSql: false,
      supportsLayerOverrides: false,
      supportsTilesAndBasicQueriesMode: true,
      supportsFieldDescriptionProperty: false,
      supportsQuantizationEditMode: false,
      supportsApplyEditsWithGlobalIds: false,
      supportsReturningQueryGeometry: false,
      advancedQueryCapabilities: {
        supportsPagination: true,
        supportsQueryAttachmentsCountOnly: false,
        supportsPaginationOnAggregatedQueries: false,
        supportsQueryRelatedPagination: false,
        supportsQueryWithDistance: false,
        supportsReturningQueryExtent: true,
        supportsStatistics: true,
        supportsOrderBy: true,
        supportsDistinct: true,
        supportsQueryWithResultType: false,
        supportsSqlExpression: false,
        supportsAdvancedQueryRelated: false,
        supportsCountDistinct: false,
        supportsPercentileStatistics: false,
        supportedSpatialAggregationStatistics: [],
        supportsLod: false,
        supportsQueryWithLodSR: false,
        supportedLodTypes: [],
        supportsReturningGeometryCentroid: false,
        supportsReturningGeometryEnvelope: false,
        supportsQueryWithDatumTransformation: false,
        supportsCurrentUserQueries: false,
        supportsHavingClause: false,
        supportsOutFieldSQLExpression: false,
        supportsMaxRecordCountFactor: false,
        supportsTopFeaturesQuery: false,
        supportsDisjointSpatialRel: false,
        supportsQueryWithCacheHint: false,
        supportedOperationsWithCacheHint: [],
        supportsQueryAnalytic: false,
        supportsDefaultSR: false,
        supportsFullTextSearch: false,
        advancedQueryAnalyticCapabilities: {},
        advancedEditingCapabilities: {},
      },
      useStandardizedQueries: true,
      allowGeometryUpdates: false,
      hasAttachments: false,
      htmlPopupType: 'esriServerHTMLPopupTypeNone',
      hasM: false,
      hasZ: false,
      objectIdField: 'OBJECTID',
      uniqueIdField: { name: 'OBJECTID', isSystemMaintained: true },
      globalIdField: '',
      typeIdField: '',
      dateFieldsTimeReference: {
        timeZone: 'UTC',
        respectsDaylightSaving: false,
      },
      preferredTimeReference: null,
      templates: [],
      supportedQueryFormats: 'JSON,geojson,PBF',
      supportedAppendFormats: '',
      supportedExportFormats: '',
      supportedSpatialRelationships: [
        'esriSpatialRelIntersects',
        'esriSpatialRelContains',
        'esriSpatialRelEnvelopeIntersects',
        'esriSpatialRelWithin',
      ],
      supportedContingentValuesFormats: '',
      hasStaticData: false,
      maxRecordCount: 2000,
      standardMaxRecordCount: 2000,
      standardMaxRecordCountNoGeometry: 2000,
      tileMaxRecordCount: 2000,
      maxRecordCountFactor: 1,
      fields: ['fields'],
      relationships: [],
      capabilities: 'list,of,stuff',
      ownershipBasedAccessControlForFeatures: { allowOthersToQuery: true },
      types: [],
      timeInfo: {},
    });
  });
});
