os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  - 10
  - lts/*
sudo: false # Enable docker-based containers
cache:
  directories: # Cache dependencies
    - node_modules

script:
  - npm test
